### ISSUE TITLE
License to reuse?

### ISSUE THREAD

**Issue by adamajm** [RalucaNicola/hiking-app#4]
Hi Raluca, can you add an Apache 2.0 or an appropriate creative commons license so we know how devs can reuse?

**Comment by RalucaNicola** [comment]
Hi Adam,

thanks for the feedback, I added an Apache 2.0 license! I am in the process of porting this repo to the esri organization, where it has a license and some updates to the npm dependencies which got pretty old by now. I'll let you know when it's ready. Hopefully I'll get to link it to the ArcGIS developers site soon...

However, if you don't have time to wait, feel free to use the code in this repo for your projects until then.
